import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
// import "./globals.css";
import "./tailwind.css"
import Navbar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-EGMREM91QB" strategy="afterInteractive" />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-EGMREM91QB');
          `}
        </Script>
      </head>
      <body className={inter.className}>
      <Navbar />
        
        
        
        {children}</body>
    </html>
  );
}
